**Numpy**

In [1]:
import numpy as np

In [2]:
result = 0
for t in range(100):
    result += t

print(result)

4950


In [3]:
w = sum([x for x in range(100)])
w

4950

In [4]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l2 = [str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

[   expresion(i)   for i in list]

In [6]:
l3 = [True,"2",3.0,4]
[type(item) for item in l3]

[bool, str, float, int]

In [7]:
x = [range(i,i+3) for i in [2,4,6]]
x

[range(2, 5), range(4, 7), range(6, 9)]

In [8]:
x = np.array([range(i,i + 3) for i in [2,3]])
x

array([[2, 3, 4],
       [3, 4, 5]])

In [9]:
x = np.array([range(i,i+3) for i in [2,4,6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**Crear matrices desde cero**

Especialmente para matrices más grandes, es más eficiente crear matrices desde cero utilizando las rutinas incorporadas en NumPy.

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
 # Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [16]:
#genera valores aleatorios entre 0 y 1
np.random.rand(3,3)

array([[0.33337536, 0.842547  , 0.65267812],
       [0.55221961, 0.21725908, 0.42397792],
       [0.26702923, 0.06145102, 0.58164266]])

In [17]:
#genera valores aleatorios entre 0 y 1 
# con media = 0 y desviacion estandar 1
np.random.randn(3,3)

array([[-1.66832555, -0.23189523,  1.21812067],
       [-1.09306244,  0.47751767,  0.38763615],
       [-1.38903684, -0.59783394,  0.05145995]])

In [18]:
# Create a 3x3 array of uniformly distributed
 # random values between 0 and 1
# np.random.random con tupla de dimensiones
np.random.random((3,3))

array([[0.33882702, 0.37697241, 0.89812667],
       [0.89653511, 0.91010139, 0.16584441],
       [0.4026951 , 0.11745756, 0.55375674]])

In [19]:
#se crea una matriz 3x3 de una distribucion normal 
# con media 0 y desviacion estandar 1
# te permite pasar por parametro la media y la desviacion esntadar
w = np.random.normal(0,1,(3,3))
w

array([[-1.47100888, -0.05754144,  0.92554444],
       [-0.03283929,  0.16462325, -0.44907606],
       [ 0.40807725,  0.99541168, -0.90596803]])

In [20]:
#se crea una matriz 3x3 de una distribucion normal 
# con media 5 y desviacion estandar 2
np.random.normal(5,2,(3,3))

array([[8.49138536, 5.62351348, 5.7544703 ],
       [6.00393185, 5.45709673, 3.31519848],
       [3.15844348, 6.08917037, 4.09308123]])

In [21]:
#creas un numero aleatorio entre inicio y final
np.random.randint(0,10)

6

In [22]:
#crea 4 valores aleatorios entre 0 y 1 
np.random.randint(0,10,size=4)

array([7, 9, 2, 0])

In [23]:
np.random.randint(10,size=4)

array([8, 0, 4, 5])

In [24]:
#creas numeros aleatorios entre inicio y final
#Pero decimos que sea de 3x3 el array
np.random.randint(0,10,(3,3))

array([[2, 0, 7],
       [4, 1, 2],
       [8, 3, 6]])

In [25]:
#crear una matriz identidad de 4x4
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**NumPy Array Attributes**


In [26]:
np.random.seed(0)

#Array
x1 = np.random.randint(10,size=6)
print(f"Este array tiene {x1.ndim} dimesion")
print("x3 shape:", x1.shape)
print("x3 size: ", x1.size)
print(x1)
print('\n')

#Matriz
x2 = np.random.randint(10,size=(3,4))
print(f"Este array tiene {x2.ndim} dimesiones")
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print(x2)
print('\n')

# Tensor tridimensional
x3 = np.random.randint(10,size=(3,4,5))
print(f"Este array tiene {x3.ndim} dimesion")
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print(x3)

Este array tiene 1 dimesion
x3 shape: (6,)
x3 size:  6
[5 0 3 3 7 9]


Este array tiene 2 dimesiones
x2 shape: (3, 4)
x2 size:  12
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Este array tiene 3 dimesion
x3 shape: (3, 4, 5)
x3 size:  60
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Array Indexing: Accessing Single Elements

In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [29]:
x1[-6]

5

In [30]:
x1[-len(x1)]

5

In [31]:
x1[-1]

9

In [32]:
for x in range(-1,-7,-1):
    print(x1[x])

9
7
3
3
0
5


**Ejercicio Matriz**

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
for i in range(len(x2)+1): #filas
    for j in range(len(x2)+1): #columnas
        print([i,j])

[0, 0]
[0, 1]
[0, 2]
[0, 3]
[1, 0]
[1, 1]
[1, 2]
[1, 3]
[2, 0]
[2, 1]
[2, 2]
[2, 3]
[3, 0]
[3, 1]
[3, 2]
[3, 3]


In [35]:
for i in range(len(x2)+1): #filas
    for j in range(len(x2[0])): #columnas
        print([i,j])

[0, 0]
[0, 1]
[0, 2]
[0, 3]
[1, 0]
[1, 1]
[1, 2]
[1, 3]
[2, 0]
[2, 1]
[2, 2]
[2, 3]
[3, 0]
[3, 1]
[3, 2]
[3, 3]


In [36]:
for i in range(len(x2)):
    for j in range(len(x2[0])):
        print(x2[i,j])

3
5
2
4
7
6
8
8
1
6
7
7


In [37]:
w = np.arange(10)
w

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
w[5:]

array([5, 6, 7, 8, 9])

In [39]:
w[4:7]

array([4, 5, 6])

In [40]:
#que rebane la lista de 2 en 2 
w[::2]

array([0, 2, 4, 6, 8])

In [41]:
#que rebane la lista de 3 en 3
w[::3]

array([0, 3, 6, 9])

In [42]:
#Aqui el dice es 1 y le suma de 2 en 2
w[1::2]

array([1, 3, 5, 7, 9])

In [43]:
w[2::2]

array([2, 4, 6, 8])

In [44]:
#todos los elementos en reversa
w[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
#rebana de 2 en 2 del 9 al 0
w[::-2]

array([9, 7, 5, 3, 1])

In [46]:
w[9::-3]

array([9, 6, 3, 0])

In [130]:
w

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
w[5::-2]

array([5, 3, 1])

In [48]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [133]:
x2[:,:]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [134]:
# :2 filas y todas las columnas
x2[:2,:]

array([[3, 5, 2, 4],
       [7, 6, 8, 8]])

In [51]:
#dos filas 1 una columna
x2[:2,:1]

array([[3],
       [7]])

In [139]:
#:3 filas y :1 columna uno
x2[:3,:1]

array([[3],
       [7],
       [1]])

In [52]:
#2 filas y 3 columnas
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

Array Slicing: Accessing Subarrays

Se usan los brackets para accesar a los elementos del array individualmente

* x[start: stop: step]

In [141]:
w[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
#star: 1, step:6 = array([1,6])
w[1::5]

array([1, 6])

In [54]:
#star: 0, step 2 en 2
w[::2]

array([0, 2, 4, 6, 8])

Multidimensional subarrays

In [146]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [148]:
#3 filas  y 2 columnas
x2[:3,:2]

array([[3, 5],
       [7, 6],
       [1, 6]])

In [150]:
#all rows, y star: 0 step:2
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [155]:
#todas las filas y columna 1 a columna 3
x2[:,::3]

array([[3, 4],
       [7, 8],
       [1, 7]])

In [154]:
"""
X2[::2] Rebana el array de la fila inicial a la numero 2
x2[::3] Rebana el array de la columna inicial a la 3

x2[::2,::3]
"""
x2[::2,::3]

array([[3, 4],
       [1, 7]])

In [164]:
"""
x2[:2] Rebana el array filtrando de fila inicial a 2
x2[::3] Rebana el array de la columna incial a la 3

"""
x2[:2,::3]

array([[3, 4],
       [7, 8]])

In [169]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [170]:
"""
x2[::2] Rebana el array filtrando de fila inicial pasando a la 2
star: 0 , step: 2

x2[::3] Rebana el array de la columna incial a la 3
star: 0 , step: 3
"""
x2[::2,::3]

array([[3, 4],
       [1, 7]])

In [173]:
#todas las filas y inicia en la columa 1 y columna 3
x2[::,::3]

array([[3, 4],
       [7, 8],
       [1, 7]])

In [59]:
#fila de 2 en 2 y columna 3
x2[::2,::3]

array([[3, 4],
       [1, 7]])

In [60]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [61]:
#de 2 en 2 e inicia en la columna 1 al final
x2[::2,1::]

array([[5, 2, 4],
       [6, 7, 7]])

In [62]:
#salto de 2 en 2 filas y valores de 3er columna
x2[::2,::3]

array([[3, 4],
       [1, 7]])

In [63]:
#salto de 2 en 2 filas y inicia en columna 2 y termina 2
x2[::2,2::2]

array([[2],
       [7]])

In [64]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [65]:
#invirtio los valores de la matriz, más no la matriz
x2[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [66]:
#invirtio los valores de la matriz y sus columnas
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

Accessing array rows and columns

In [72]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [116]:
x2[::,0]

array([3, 7, 1])

In [74]:
#todas las filas y columna 0
print(x2[:,0])

[3 7 1]


In [102]:
print(x2[:,1])

[5 6 6]


In [103]:
print(x2[0,:])

[3 5 2 4]


Subarrays as no-copy views

In [117]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [129]:
x2_sub = x2[:3,:1]
x2_sub

array([[3],
       [7],
       [1]])